cookie:
  expiry_days: 30
  key: asset_survey_auth_cookie_key_2024
  name: asset_survey_auth
credentials:
  usernames:
    admin:
      email: admin@petrokimia.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: User
      logged_in: true
      password: $2b$12$PnZ90PewnJvw/d15jV3FTup7aGO67Wue1S2Rj5PgtCoL.wKmCfrO.
      roles:
      - admin
    surveyor:
      email: surveyor@petrokimia.com
      failed_login_attempts: 0
      first_name: Surveyor
      last_name: Lapangan
      logged_in: false
      password: $2b$12$V2eXKYDgumzjwPKvrP1SZ.JQII2oGJTr2NO2w/tAerffg7DGdFxLG
      roles:
      - surveyor
